apply plugin: 'com.android.application'

android {
    namespace 'com.dom.bilidownloader'
    compileSdk 34

    defaultConfig {
        applicationId "com.dom.bilidownloader"
        minSdk 24
        targetSdk 34
        versionCode 11
        versionName "1.2.0"
    }

    signingConfigs {
        release {
            storeFile file('../bili-release.keystore')
            storePassword 'dom2026bili'
            keyAlias 'bili'
            keyPassword 'dom2026bili'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
